server:
  port: 8899
spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true
  jpa:
    database: MYSQL
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver